RFS_NAME: 'minio' # 遠端儲存體名稱，需與 server/.env 的 RFS_NAME 相同


# 排程資源設定
# "flow_name/deploy_name" 必須唯一，可以從 Prefect Server 檢查現有的名稱
deployment:
  flow_py_name: prefect_flow.py    # flow.py 的檔名
  flow_name: main                  # 專案名稱，需要與 flow.py 中「@flow」裝飾的function名稱 相同
  deploy_name: model_training      # 排程目的，如：daliy_model、data_update等
  pool_name: default-agent-pool    # 資源池設定，使用 flow_agent 建立的 工作流程的執行服務
  queue_name: ml                   # 專案名稱

# 排程時間設定
scheduler:
  # 主要設定
  method: 'rrule'                  # 排程時間的設定方式，可選擇：interval，cron，或 rrule
  timezone: 'Asia/Taipei'          # 時區設定，如：'Asia/Taipei'、'UTC'
  # 細部設定，只有上方 method 選擇的對應設定會被採用
  interval: 60                     # 單位：秒
  cron: '1 * * * *'
  rrule: 'FREQ=WEEKLY;BYDAY=MO,WE,FR;UNTIL=20240730T040000Z'

  # 如何設定 cron & rrule 請參考下方連結
  # https://docs.prefect.io/2.10.21/concepts/schedules/